version: '3'

services:

  mongo:
    image: mongo:3.4
    restart: unless-stopped
    networks:
      - wake_cap_network
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb
    ports:
      - "27017:27017"

  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - wake_cap_network
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT= 3000
      - MONGO_URL=mongodb://mongo:27017/wake_cap_db
    ports:
      - "3000:3000"

networks:
  wake_cap_network:
    driver: "bridge"

volumes:
  mongodata:
    driver: local
  mongoconfig:
    driver: local
